# PowerSync Cloud config (fetched from cloud)
# yaml-language-server: $schema=https://unpkg.com/@powersync/cli-schemas@latest/json-schema/service-config.json
_type: cloud
name: mango
region: us
replication:
  connections:
    - type: mongodb
      name: default
      tag: default
      username: steven
      password:
        secret_ref: default_password
      database: powersync
      uri: !env MONGO_URI
      post_images: auto_configure
client_auth:
  jwks:
    keys: []
  supabase: false
  additional_audiences: []
  allow_temporary_tokens: true

#   PowerSync will use the same JWT secret as Supabase.
#   supabase: false

#   Legacy: If your Supabase project does not use the new JWT signing keys, you must provide your project's legacy JWT secret to use Supabase Auth. Get it from your project's API settings in the Supabase Dashboard.
#   supabase_jwt_secret:
#     secret: !env POWERSYNC_SUPABASE_JWT_SECRET

#   Additional audiences to accept when validating incoming JWT tokens (the instance domain is always accepted)
#   additional_audiences: []

#   Enables development tokens to be generated and accepted by the instance
#   allow_temporary_tokens: false

#   URL to a JSON Web Key Set (JWKS) endpoint; the instance fetches public keys from this URL to verify JWT signatures from clients.
#   jwks_uri: https://example.com/jwks.json
#   Inline JSON Web Key Set; provide keys directly instead of (or in addition to) jwks_uri to verify JWT signatures.
#   jwks:
#     keys:
#       HMAC (symmetric) – Options: HS256 | HS384 | HS512
#       - kty: oct
#         alg: HS256
#         kid: example-key
#         k:
#           secret: !env POWERSYNC_CLIENT_AUTH_KEY
#       RSA – Options for alg: RS256 | RS384 | RS512
#       - kty: RSA
#         kid: my-rsa-key
#         n: "<base64url-modulus>"
#         e: "<base64url-exponent>"
#         alg: RS256
#       EC – Options for crv: P-256 | P-384 | P-512; alg: ES256 | ES384 | ES512
#       - kty: EC
#         kid: my-ec-key
#         crv: P-256
#         x: "<base64url-x>"
#         y: "<base64url-y>"
#         alg: ES256
#       OKP (EdDSA) – Options for crv: Ed25519 | Ed448
#       - kty: OKP
#         kid: my-okp-key
#         crv: Ed25519
#         x: "<base64url-public-key>"
#         alg: EdDSA
