import * as jose from 'jose';

const KID = 'dev-key-1';
const ISSUER = 'powersync-demo-app';
const EXPIRES_IN = '1h';

/**
 * Generate a JWT for PowerSync auth using the shared HS256 secret.
 * Demo only – in production, tokens should be generated by a secure backend.
 */
export async function generateToken(options: { endpoint: string; secret: string; userId: string; }): Promise<string> {
  const { endpoint, secret, userId } = options;

  // PS_CLIENT_AUTH_KEY is base64url-encoded; decode to raw bytes for signing
  const secretBytes = Buffer.from(secret, 'base64url');

  return new jose.SignJWT({})
    .setProtectedHeader({ alg: 'HS256', kid: KID })
    .setSubject(userId)
    .setIssuer(ISSUER)
    .setAudience(endpoint)
    .setIssuedAt()
    .setExpirationTime(EXPIRES_IN)
    .sign(secretBytes);
}
