#!/bin/sh
set -e

if git diff --cached --quiet --diff-filter=ACMR; then
	exit 0
fi

git diff --cached --name-only -z --diff-filter=ACMR \
	| xargs -0 pnpm prettier --write --ignore-unknown

pnpm lint:fix

git diff --cached --name-only -z --diff-filter=ACMR \
	| xargs -0 git add --
