name: Manually Build CLI Installers for Testing

on:
  workflow_dispatch:
    inputs:
      retention-days:
        description: 'Number of days to retain uploaded artifacts'
        type: number
        default: 7

jobs:
  build-artifacts:
    uses: ./.github/workflows/buildArtifacts.yml
    with:
      retention-days: ${{ inputs.retention-days || 7 }}
